
package webserviceDemoClient.com.hyman;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "myService", targetNamespace = "http://www.hyman.com", wsdlLocation = "http://127.0.0.1/serviceTest?wsdl")
public class MyService
    extends Service
{

    private final static URL MYSERVICE_WSDL_LOCATION;
    private final static WebServiceException MYSERVICE_EXCEPTION;
    private final static QName MYSERVICE_QNAME = new QName("http://www.hyman.com", "myService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1/serviceTest?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYSERVICE_WSDL_LOCATION = url;
        MYSERVICE_EXCEPTION = e;
    }

    public MyService() {
        super(__getWsdlLocation(), MYSERVICE_QNAME);
    }

    public MyService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYSERVICE_QNAME, features);
    }

    public MyService(URL wsdlLocation) {
        super(wsdlLocation, MYSERVICE_QNAME);
    }

    public MyService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYSERVICE_QNAME, features);
    }

    public MyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SendService
     */
    @WebEndpoint(name = "SendServicePort")
    public SendService getSendServicePort() {
        return super.getPort(new QName("http://www.hyman.com", "SendServicePort"), SendService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SendService
     */
    @WebEndpoint(name = "SendServicePort")
    public SendService getSendServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.hyman.com", "SendServicePort"), SendService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYSERVICE_EXCEPTION!= null) {
            throw MYSERVICE_EXCEPTION;
        }
        return MYSERVICE_WSDL_LOCATION;
    }

}
