
package WebserviceSourceDemo.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GHBackBone_UploadToCitySoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GHBackBoneUploadToCitySoap {


    /**
     * ͬ����Ա�Ļ�����Ϣ������String��0Ϊ�ɹ� ��1�������쳣����ֵΪʧ��
     * 
     * @param xml
     * @param qyCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UploadWorker", action = "http://tempuri.org/UploadWorker")
    @WebResult(name = "UploadWorkerResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UploadWorker", targetNamespace = "http://tempuri.org/", className = "UploadWorker")
    @ResponseWrapper(localName = "UploadWorkerResponse", targetNamespace = "http://tempuri.org/", className = "UploadWorkerResponse")
    public String uploadWorker(
            @WebParam(name = "xml", targetNamespace = "http://tempuri.org/")
                    String xml,
            @WebParam(name = "qyCode", targetNamespace = "http://tempuri.org/")
                    String qyCode);

    /**
     * ͬ���ν���ҵ�Ļ�����Ϣ������String��0Ϊ�ɹ� ��1�������쳣����ֵΪʧ��
     * 
     * @param xml
     * @param qyCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UploadQyxx", action = "http://tempuri.org/UploadQyxx")
    @WebResult(name = "UploadQyxxResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UploadQyxx", targetNamespace = "http://tempuri.org/", className = "UploadQyxx")
    @ResponseWrapper(localName = "UploadQyxxResponse", targetNamespace = "http://tempuri.org/", className = "UploadQyxxResponse")
    public String uploadQyxx(
            @WebParam(name = "xml", targetNamespace = "http://tempuri.org/")
                    String xml,
            @WebParam(name = "qyCode", targetNamespace = "http://tempuri.org/")
                    String qyCode);

    /**
     * ͬ����Ŀ�Ļ�����Ϣ������String��0Ϊ�ɹ� ��1�������쳣����ֵΪʧ��
     * 
     * @param xml
     * @param qyCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UploadProject", action = "http://tempuri.org/UploadProject")
    @WebResult(name = "UploadProjectResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UploadProject", targetNamespace = "http://tempuri.org/", className = "UploadProject")
    @ResponseWrapper(localName = "UploadProjectResponse", targetNamespace = "http://tempuri.org/", className = "UploadProjectResponse")
    public String uploadProject(
            @WebParam(name = "xml", targetNamespace = "http://tempuri.org/")
                    String xml,
            @WebParam(name = "qyCode", targetNamespace = "http://tempuri.org/")
                    String qyCode);

    /**
     * ͬ����Ŀ���ù���Ϣ������String��0Ϊ�ɹ� ��1�������쳣����ֵΪʧ��
     * 
     * @param xml
     * @param qyCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UploadProject_Worker", action = "http://tempuri.org/UploadProject_Worker")
    @WebResult(name = "UploadProject_WorkerResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UploadProject_Worker", targetNamespace = "http://tempuri.org/", className = "UploadProjectWorker")
    @ResponseWrapper(localName = "UploadProject_WorkerResponse", targetNamespace = "http://tempuri.org/", className = "UploadProjectWorkerResponse")
    public String uploadProjectWorker(
            @WebParam(name = "xml", targetNamespace = "http://tempuri.org/")
                    String xml,
            @WebParam(name = "qyCode", targetNamespace = "http://tempuri.org/")
                    String qyCode);

    /**
     * ͬ�����˿�����Ϣ������String��0Ϊ�ɹ� ��1�������쳣����ֵΪʧ��
     * 
     * @param xml
     * @param qyCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UploadWorkerKqxx", action = "http://tempuri.org/UploadWorkerKqxx")
    @WebResult(name = "UploadWorkerKqxxResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UploadWorkerKqxx", targetNamespace = "http://tempuri.org/", className = "UploadWorkerKqxx")
    @ResponseWrapper(localName = "UploadWorkerKqxxResponse", targetNamespace = "http://tempuri.org/", className = "UploadWorkerKqxxResponse")
    public String uploadWorkerKqxx(
            @WebParam(name = "xml", targetNamespace = "http://tempuri.org/")
                    String xml,
            @WebParam(name = "qyCode", targetNamespace = "http://tempuri.org/")
                    String qyCode);

    /**
     * ͬ�����˹��ʿ���Ϣ������String��0Ϊ�ɹ� ��1�������쳣����ֵΪʧ��
     * 
     * @param xml
     * @param qyCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UploadWorkerBankCard", action = "http://tempuri.org/UploadWorkerBankCard")
    @WebResult(name = "UploadWorkerBankCardResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UploadWorkerBankCard", targetNamespace = "http://tempuri.org/", className = "UploadWorkerBankCard")
    @ResponseWrapper(localName = "UploadWorkerBankCardResponse", targetNamespace = "http://tempuri.org/", className = "UploadWorkerBankCardResponse")
    public String uploadWorkerBankCard(
            @WebParam(name = "xml", targetNamespace = "http://tempuri.org/")
                    String xml,
            @WebParam(name = "qyCode", targetNamespace = "http://tempuri.org/")
                    String qyCode);

    /**
     * ͬ����λ������Ϣ������String��0Ϊ�ɹ� ��1�������쳣����ֵΪʧ��
     * 
     * @param xml
     * @param qyCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UploadWorkerSkill", action = "http://tempuri.org/UploadWorkerSkill")
    @WebResult(name = "UploadWorkerSkillResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UploadWorkerSkill", targetNamespace = "http://tempuri.org/", className = "UploadWorkerSkill")
    @ResponseWrapper(localName = "UploadWorkerSkillResponse", targetNamespace = "http://tempuri.org/", className = "UploadWorkerSkillResponse")
    public String uploadWorkerSkill(
            @WebParam(name = "xml", targetNamespace = "http://tempuri.org/")
                    String xml,
            @WebParam(name = "qyCode", targetNamespace = "http://tempuri.org/")
                    String qyCode);

    /**
     * ͬ��ʶ��������Ϣ������String��0Ϊ�ɹ� ��1�������쳣����ֵΪʧ��
     * 
     * @param xml
     * @param qyCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UploadWorkerFeature", action = "http://tempuri.org/UploadWorkerFeature")
    @WebResult(name = "UploadWorkerFeatureResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UploadWorkerFeature", targetNamespace = "http://tempuri.org/", className = "UploadWorkerFeature")
    @ResponseWrapper(localName = "UploadWorkerFeatureResponse", targetNamespace = "http://tempuri.org/", className = "UploadWorkerFeatureResponse")
    public String uploadWorkerFeature(
            @WebParam(name = "xml", targetNamespace = "http://tempuri.org/")
                    String xml,
            @WebParam(name = "qyCode", targetNamespace = "http://tempuri.org/")
                    String qyCode);

    /**
     * ͬ�����ʱ�֤����Ϣ������String��0Ϊ�ɹ� ��1�������쳣����ֵΪʧ��
     * 
     * @param xml
     * @param qyCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UploadWageMargin", action = "http://tempuri.org/UploadWageMargin")
    @WebResult(name = "UploadWageMarginResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UploadWageMargin", targetNamespace = "http://tempuri.org/", className = "UploadWageMargin")
    @ResponseWrapper(localName = "UploadWageMarginResponse", targetNamespace = "http://tempuri.org/", className = "UploadWageMarginResponse")
    public String uploadWageMargin(
            @WebParam(name = "xml", targetNamespace = "http://tempuri.org/")
                    String xml,
            @WebParam(name = "qyCode", targetNamespace = "http://tempuri.org/")
                    String qyCode);

    /**
     * ͬ������ר����Ϣ������String��0Ϊ�ɹ� ��1�������쳣����ֵΪʧ��
     * 
     * @param xml
     * @param qyCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UploadSpecialAccount", action = "http://tempuri.org/UploadSpecialAccount")
    @WebResult(name = "UploadSpecialAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UploadSpecialAccount", targetNamespace = "http://tempuri.org/", className = "UploadSpecialAccount")
    @ResponseWrapper(localName = "UploadSpecialAccountResponse", targetNamespace = "http://tempuri.org/", className = "UploadSpecialAccountResponse")
    public String uploadSpecialAccount(
            @WebParam(name = "xml", targetNamespace = "http://tempuri.org/")
                    String xml,
            @WebParam(name = "qyCode", targetNamespace = "http://tempuri.org/")
                    String qyCode);

    /**
     * ͬ���ù���ͬ��Ϣ������String��0Ϊ�ɹ� ��1�������쳣����ֵΪʧ��
     * 
     * @param xml
     * @param qyCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UploadContract", action = "http://tempuri.org/UploadContract")
    @WebResult(name = "UploadContractResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UploadContract", targetNamespace = "http://tempuri.org/", className = "UploadContract")
    @ResponseWrapper(localName = "UploadContractResponse", targetNamespace = "http://tempuri.org/", className = "UploadContractResponse")
    public String uploadContract(
            @WebParam(name = "xml", targetNamespace = "http://tempuri.org/")
                    String xml,
            @WebParam(name = "qyCode", targetNamespace = "http://tempuri.org/")
                    String qyCode);

    /**
     * ͬ�����ʽ�����Ϣ������String��0Ϊ�ɹ� ��1�������쳣����ֵΪʧ��
     * 
     * @param xml
     * @param qyCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UploadSalary", action = "http://tempuri.org/UploadSalary")
    @WebResult(name = "UploadSalaryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UploadSalary", targetNamespace = "http://tempuri.org/", className = "UploadSalary")
    @ResponseWrapper(localName = "UploadSalaryResponse", targetNamespace = "http://tempuri.org/", className = "UploadSalaryResponse")
    public String uploadSalary(
            @WebParam(name = "xml", targetNamespace = "http://tempuri.org/")
                    String xml,
            @WebParam(name = "qyCode", targetNamespace = "http://tempuri.org/")
                    String qyCode);

    /**
     * ͬ��������ѵ��Ϣ������String��0Ϊ�ɹ� ��1�������쳣����ֵΪʧ��
     * 
     * @param xml
     * @param qyCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UploadTrain", action = "http://tempuri.org/UploadTrain")
    @WebResult(name = "UploadTrainResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UploadTrain", targetNamespace = "http://tempuri.org/", className = "UploadTrain")
    @ResponseWrapper(localName = "UploadTrainResponse", targetNamespace = "http://tempuri.org/", className = "UploadTrainResponse")
    public String uploadTrain(
            @WebParam(name = "xml", targetNamespace = "http://tempuri.org/")
                    String xml,
            @WebParam(name = "qyCode", targetNamespace = "http://tempuri.org/")
                    String qyCode);

    /**
     * ͬ����������Ϣ������String��0Ϊ�ɹ� ��1�������쳣����ֵΪʧ��
     * 
     * @param xml
     * @param qyCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UploadEvaluate", action = "http://tempuri.org/UploadEvaluate")
    @WebResult(name = "UploadEvaluateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UploadEvaluate", targetNamespace = "http://tempuri.org/", className = "UploadEvaluate")
    @ResponseWrapper(localName = "UploadEvaluateResponse", targetNamespace = "http://tempuri.org/", className = "UploadEvaluateResponse")
    public String uploadEvaluate(
            @WebParam(name = "xml", targetNamespace = "http://tempuri.org/")
                    String xml,
            @WebParam(name = "qyCode", targetNamespace = "http://tempuri.org/")
                    String qyCode);

    /**
     * ͬ���ල�����Ϣ������String��0Ϊ�ɹ� ��1�������쳣����ֵΪʧ��
     * 
     * @param xml
     * @param qyCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UploadSpecialExamine", action = "http://tempuri.org/UploadSpecialExamine")
    @WebResult(name = "UploadSpecialExamineResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UploadSpecialExamine", targetNamespace = "http://tempuri.org/", className = "UploadSpecialExamine")
    @ResponseWrapper(localName = "UploadSpecialExamineResponse", targetNamespace = "http://tempuri.org/", className = "UploadSpecialExamineResponse")
    public String uploadSpecialExamine(
            @WebParam(name = "xml", targetNamespace = "http://tempuri.org/")
                    String xml,
            @WebParam(name = "qyCode", targetNamespace = "http://tempuri.org/")
                    String qyCode);

    /**
     * ͬ�����˺�����������String��0Ϊ�ɹ� ��1�������쳣����ֵΪʧ��
     * 
     * @param xml
     * @param qyCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UploadBlacklist_Woker", action = "http://tempuri.org/UploadBlacklist_Woker")
    @WebResult(name = "UploadBlacklist_WokerResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UploadBlacklist_Woker", targetNamespace = "http://tempuri.org/", className = "UploadBlacklistWoker")
    @ResponseWrapper(localName = "UploadBlacklist_WokerResponse", targetNamespace = "http://tempuri.org/", className = "UploadBlacklistWokerResponse")
    public String uploadBlacklistWoker(
            @WebParam(name = "xml", targetNamespace = "http://tempuri.org/")
                    String xml,
            @WebParam(name = "qyCode", targetNamespace = "http://tempuri.org/")
                    String qyCode);

}
