
package WebserviceSourceDemo.tempuri;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GHBackBone_UploadToCity", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://218.4.84.171:5445/AppWebServiceTest/GHBackBone_UploadToCity.asmx?WSDL")
public class GHBackBoneUploadToCity
    extends Service
{

    private final static URL GHBACKBONEUPLOADTOCITY_WSDL_LOCATION;
    private final static WebServiceException GHBACKBONEUPLOADTOCITY_EXCEPTION;
    private final static QName GHBACKBONEUPLOADTOCITY_QNAME = new QName("http://tempuri.org/", "GHBackBone_UploadToCity");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://218.4.84.171:5445/AppWebServiceTest/GHBackBone_UploadToCity.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GHBACKBONEUPLOADTOCITY_WSDL_LOCATION = url;
        GHBACKBONEUPLOADTOCITY_EXCEPTION = e;
    }

    public GHBackBoneUploadToCity() {
        super(__getWsdlLocation(), GHBACKBONEUPLOADTOCITY_QNAME);
    }

    public GHBackBoneUploadToCity(WebServiceFeature... features) {
        super(__getWsdlLocation(), GHBACKBONEUPLOADTOCITY_QNAME, features);
    }

    public GHBackBoneUploadToCity(URL wsdlLocation) {
        super(wsdlLocation, GHBACKBONEUPLOADTOCITY_QNAME);
    }

    public GHBackBoneUploadToCity(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GHBACKBONEUPLOADTOCITY_QNAME, features);
    }

    public GHBackBoneUploadToCity(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GHBackBoneUploadToCity(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GHBackBoneUploadToCitySoap
     */
    @WebEndpoint(name = "GHBackBone_UploadToCitySoap")
    public GHBackBoneUploadToCitySoap getGHBackBoneUploadToCitySoap() {
        return super.getPort(new QName("http://tempuri.org/", "GHBackBone_UploadToCitySoap"), GHBackBoneUploadToCitySoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GHBackBoneUploadToCitySoap
     */
    @WebEndpoint(name = "GHBackBone_UploadToCitySoap")
    public GHBackBoneUploadToCitySoap getGHBackBoneUploadToCitySoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "GHBackBone_UploadToCitySoap"), GHBackBoneUploadToCitySoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GHBACKBONEUPLOADTOCITY_EXCEPTION!= null) {
            throw GHBACKBONEUPLOADTOCITY_EXCEPTION;
        }
        return GHBACKBONEUPLOADTOCITY_WSDL_LOCATION;
    }

}
