
package webserviceDemoClient.collection;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CollectionWS", targetNamespace = "http://webserviceDemo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CollectionWS {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rtnMethod", targetNamespace = "http://webserviceDemo/", className = "webserviceDemoClient.collection.RtnMethod")
    @ResponseWrapper(localName = "rtnMethodResponse", targetNamespace = "http://webserviceDemo/", className = "webserviceDemoClient.collection.RtnMethodResponse")
    @Action(input = "http://webserviceDemo/CollectionWS/rtnMethodRequest", output = "http://webserviceDemo/CollectionWS/rtnMethodResponse")
    public List<String> rtnMethod();

}
